### ISSUE TITLE
error: cannot find 'AppsFlyerAttribution' in scope

### ISSUE THREAD

**Issue by wangxingxing123654** [AppsFlyerSDK/appsflyer-flutter-plugin#119]

**Comment by GM-appsflyer** [comment]
Hey @wangxingxing123654 ,

Could you elaborate on the issue?
What is the plugin version that's being used + logs showing the error.

**Comment by antoinepemeja** [comment]
Hello,
I have similar issue, I updated AppsFlyer with cocoapods
`Installing AppsFlyerFramework 6.2.6 (was 4.11.2)`

Then I renamed "AppsFlyerTracker" to "AppsFlyerLib" and changed the import.
I removed derived data, clean my project, pod deintegrate, but the problem persist.

In AppDelegate I have this warning:
`Use of 'AppsFlyerLib' refers to instance method rather than class 'AppsFlyerLib' in module 'AppsFlyerLib'`

context: Xcode Version 12.5 (12E262), Swift 5

Thank you for your help

**Comment by wangxingxing123654** [comment]
> Hey @wangxingxing123654 ,
> 
> Could you elaborate on the issue?
> What is the plugin version that's being used + logs showing the error.


v6.2.4+1-flutterv1

**Comment by GM-appsflyer** [comment]
Could you try and see if this error appears on v6.2.6-nullsafety.1?

**Comment by GM-appsflyer** [comment]
Closing this issue, please reach out if you still encounter this issue!
