### ISSUE TITLE
Deeplink class parameter missing

### ISSUE THREAD

**Issue by esentis** [AppsFlyerSDK/appsflyer-flutter-plugin#226]
The `Deeplink` class is missing the `deep_link_sub1`, and the only way to access it is through the `toJson` method `.toJson()['deepLink']['deep_link_sub1']`. 

### Solution

Add below line in `DeepLink` class
```dart
 String? get deepLinkSubValue =>  _clickEvent["deep_link_sub1"] as String?;
```

**Comment by pazlavi** [comment]
Hi @esentis 
Thank you for reaching out to us.
There is no getter for this property by design. 
For extracting this field you should use the `getStringValue` method. 
```dart
    _appsflyerSdk?.onDeepLinking((DeepLinkResult dp) {
      var deepLinkSub1 = dp.deepLink?.getStringValue("deep_link_sub1");
    });
```
You can find more details about how to work with the DeepLinkResult object [here](https://dev.appsflyer.com/hc/docs/unified-deep-linking-udl)
